"""Add auth0_id field to Users table

Revision ID: 1425c896d3ef
Revises: cb16ae472c1e
Create Date: 2025-05-10 00:12:00.358973

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1425c896d3ef'
down_revision = 'cb16ae472c1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('auth0_id', sa.String(), nullable=True))

    op.alter_column('user', 'hashed_password',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.create_index(op.f('ix_user_auth0_id'), 'user', ['auth0_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_auth0_id'), table_name='user')
    op.drop_column('user', 'auth0_id')
    op.alter_column('user', 'hashed_password',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    # ### end Alembic commands ###
