services:
  web:
    image: 4ndresor/flashcards_api
    container_name: fastapi_app
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  celery:
    image: 4ndresor/flashcards_api
    container_name: celery_worker
    command: celery -A celery_worker.celery worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis

  celery-flower:
    image: mher/flower
    container_name: celery-flower
    ports:
      - "5555:5555"
    command: celery --broker=redis://redis:6379/0 flower --port=5555
    env_file:
      - .env
    depends_on:
      - redis
